site_name: Jellobot Documentation
site_url: "https://jellobot-docs.pages.dev"
theme:
  name: material
  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: 'index.md'
  - App:
    - 'Discord Bot': './app/app.md'
  - Examples:
    - './examples/class_and_function.md'
    - './examples/fullsupport_docstring.md'
    - './examples/functions.md'
    - './examples/subfolder':
            - './examples/subfolder/functions.md'

markdown_extensions:
    - toc:
        toc_depth: 3
        permalink: True
    - extra
    - smarty
    - codehilite
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.emoji
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    
